production:
 create_from_remote: no
 use.user.selected.activities: yes

development:
 encounter_privilege_map: Procedures done:Manage procedures done;Outpatient diagnosis:Manage outpatient diagnoses,Update hiv status:Manage HIV Status Visits,Vitals:Manage Vitals,Give drugs:Manage Give Drugs,Lab orders:Manage Lab Orders
 application_diagnosis_concept: QECH Emergency Diagnosis List
 application_generic_medication: Diabetes Medication
 use.filing.number: false
 filing.number.limit: 300
 create_from_remote: no
 use.user.selected.activities: false
 advanced.prescription.interface: true
 auto_set_appointment: false
 is_referral_centre: false

test: &TEST
 create_from_remote: no
 use.user.selected.activities: yes

cucumber:
  <<: *TEST
