production:
 create_from_remote: no
 use.user.selected.activities: yes

development:
 encounter_privilege_map: Outpatient diagnosis:Manage diabetes history,Update hiv status:Manage HIV Status Visits,Vitals:Manage Vitals,Give drugs:Manage Give Drugs,Lab orders:Manage Lab Orders
 application_diagnosis_concept: QECH Emergency Diagnosis List
 application_generic_medication: Diabetes Medication
 filing.number.limit: 300
 create_from_remote: no
 use.user.selected.activities: false
 advanced.prescription.interface: true
 auto_set_appointment: false

test: &TEST
 create_from_remote: no
 use.user.selected.activities: yes

cucumber:
  <<: *TEST
